### PR TITLE
Fix missing blocks.ByHeightFrom in FVM environment

### LINKED ISSUE #102: Implement GetBlockAtHeight for Archive Node invoker
## Problem
Some flow batch scanner scripts fail on the Archive node because thefvm instance in the the invoker module of the archive node does not implement methods like GetBlockAtHeight and GetAccount

## Solution
Implement these methods and bugfix the errors caused by a GetAccount calls in the fvm

## Testing
The flow-batch-scanner example scripts should produce the same output as Execution nodes

### PR DESCRIPTION
**Pull request by koko1123**
## Goal of this PR
Add WithBlocks interface to `Script` and `GetAccount` fvm contexts
Fixes #102

### CODE REVIEW

**Review by zhangchiqing — APPROVED** [review]

File: service/invoker/invoker.go [hunk 1]
```diff
@@ -188,3 +193,23 @@ func (i *Invoker) Script(height uint64, script []byte, arguments []cadence.Value
...
+		return header, nil
+	}
+
+	if height > header.Height {
+		minHeight, err := i.index.First()
+		if err != nil {
+			return nil, fmt.Errorf("could not find first indexed height: %w", err)
+		}
+		// imitate flow-go error format
+		msg := fmt.Sprintf("requested height (%d) is not in the range(%d, %d)", height, minHeight, header.Height)
```
Comment (pattyshack) [inline service/invoker/invoker.go:209]: don't need this extra format step.  just pass the template string and arguments directly into NewValueErrorf

**Review by pattyshack — APPROVED** [review]

File: service/invoker/invoker.go (hunk 1 above)
Comment (koko1123) [reply service/invoker/invoker.go]: Done!
