### PR TITLE
Add bug fix for missing register value for heights

### LINKED ISSUE #81: [BUG] Archive node should only return state query up to indexed height
### Current Behavior

Let's say latest block is 1000, register A is updated at height 500 and 700:with the following value:
```
height 500: register A is 3
height 700: register A is 4
```
When archive node is catching up, and indexed up to height 600, and we run a state query against it to get state for block 800, then it would thought it has indexed all (which is wrong, because it only indexed up to block 600), and would return register A's value as 3 for block 800, which is wrong

### Expected Behavior

If archive node has indexed up height 600, it should return not found for state query against any block above 600, such as 800

### Steps To Reproduce

use mainnet staging and flow-archive-access validator

### Environment

```markdown
`v0.29-concurrent-importing-simplify-logs` on flow-archive
```

### What are you currently working on that this is blocking?

_No response_

### PR DESCRIPTION
**Pull request by koko1123**
## Goal of this PR
Add sentinel check for last indexed height so we're always returning correct values
Fixes #81

### CODE REVIEW

File: service/invoker/invoker.go [hunk 1]
```diff
@@ -177,3 +187,14 @@ func (i *Invoker) Script(height uint64, script []byte, arguments []cadence.Value
...
 }
+
+func (i *Invoker) validateHeightIndexed(height uint64) error {
+	h, err := i.index.Last()
+	if err != nil {
+		return fmt.Errorf("could not get last indexed height for Archive node")
+	}
+	if h < height {
+		return fmt.Errorf("current indexed height(%d) lower than requested height", h)
+	}
```
Comment (zhangchiqing) [inline service/invoker/invoker.go:198]:
```suggestion
	if height > h {
		return fmt.Errorf("the requested height (%d) is beyond the highest indexed height(%d)", height, h)
	}
```

File: api/archive/server.go [hunk 2]
```diff
@@ -466,3 +474,14 @@ func (s *Server) ListSealsForHeight(ctx context.Context, req *ListSealsForHeight
...
 }
+
+func (s *Server) validateHeightIndexed(height uint64) error {
+	h, err := s.index.Last()
+	if err != nil {
+		return fmt.Errorf("could not get last indexed height for Archive node")
+	}
+	if h < height {
+		return fmt.Errorf("current indexed height(%d) lower than requested height", h)
+	}
```
Comment (zhangchiqing) [inline api/archive/server.go:485]:
```suggestion
	if height > h {
		return fmt.Errorf("the requested height (%d) is beyond the highest indexed height(%d)", height, h)
	}
```

**Review by zhangchiqing — APPROVED** [review]

File: service/invoker/invoker.go [hunk 3]
```diff
@@ -177,3 +187,14 @@ func (i *Invoker) Script(height uint64, script []byte, arguments []cadence.Value
 
 	return proc.Value, nil
 }
+
+func (i *Invoker) validateHeightIndexed(height uint64) error {
```
Comment (SaveTheRbtz) [inline service/invoker/invoker.go:191]: given that we duplicate this code, should it be a part of the `index` access itself?  Otherwise index usage would be quite error-prone and involve not forgetting to call `validateHeightIndexed`.

File: service/invoker/invoker_internal_test.go [hunk 4]
```diff
@@ -112,6 +112,22 @@ func TestInvoker_Script(t *testing.T) {
...
+		index.LastFunc = func() (uint64, error) {
+			return mocks.GenericHeight - 1, nil
+		}
+
+		invoke := baselineInvoker(t)
+		invoke.index = index
+
+		_, err := invoke.Script(mocks.GenericHeight, mocks.GenericBytes, []cadence.Value{})
+
+		assert.Error(t, err)
```
Comment (SaveTheRbtz) [inline service/invoker/invoker_internal_test.go:128]: to be a bit more robust you likely want to check for the specific error type/text.

**Review by janezpodhostnik — APPROVED** [review]
+1 on open suggestions

File: service/invoker/invoker.go (hunk 3 above)
Comment (koko1123) [reply service/invoker/invoker.go:191]: So I thought of this earlier and had two problems with it:
- `ReadRegister`, the function we want to guard for script exec is not in the `index` module: 
https://github.com/onflow/flow-archive/blob/2be1d7f579efc8d16dcd9ca2b8c8cec4611a596a/service/invoker/read.go
- for the index functions, I wasn't sure if we should implement this guard for every lookup by height, including `SealsByHeight`, `TransactionsByHeight`, `CollectionsByHeight` etc. 

So I went with this duplicating approach to only guard where relevant to avoid more surgery. 

That said, I've moved it to a util so we can use it in `index` if we decide to go that way later on

File: service/invoker/invoker_internal_test.go (hunk 4 above)
Comment (koko1123) [reply service/invoker/invoker_internal_test.go:130]: Done!
